name: Download and Make

on:
  schedule:
    - cron: "0 20 * * *" #runs at 00:00 UTC everyday
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libtiff6 \
            libgeos-dev \
            libproj-dev \
            proj-data \
            proj-bin \
            libgdal-dev \
            python3-gdal \
            python3-pyproj \
            libcurl4-openssl-dev \
            build-essential

      - name: Update Conda
        run: $CONDA/bin/conda update -n base -c defaults conda
  
      - name: Install dependencies
        run: |
          $CONDA/bin/conda env create -f environment.yaml
          source $CONDA/bin/activate environment
          $CONDA/bin/conda install -c conda-forge cartopy pyproj shapely --force-reinstall

      - name: execute py script
        run: |
          source $CONDA/bin/activate environment
          python downloadNC.py

      - name: Use Node.js
        uses: actions/setup-node@v3
      - run: npm install
      - name: "Run Node script with NODE_OPTIONS to allow deprecated SSL"
        env:
          NODE_OPTIONS: "--openssl-legacy-provider"
        run: npm run build --if-present

      - name: Commit files
        id: commit
        run: |
          git config --local user.email "action[bot]@github.com"
          git config --local user.name "github-actions[bot]"
          git add --all
          git commit -m "Add changes" -a
          git push
        shell: bash