name: Download and Make

on:
  schedule:
    - cron: "0 20 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Install system libraries and create symlink
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgdal-dev \
            libgeos-dev \
            libproj-dev \
            libtiff6 \
            python3-gdal \
            python3-pyproj \
            proj-bin \
            proj-data
          # Create symlink from libtiff6 to libtiff5
          sudo ln -s /usr/lib/x86_64-linux-gnu/libtiff.so.6 /usr/lib/x86_64-linux-gnu/libtiff.so.5

      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yaml
          cache-environment: true
          create-args: >-
            python=3.9
            --channel conda-forge
          
      - name: Verify environment
        shell: bash -l {0}
        run: |
          micromamba list
          python -c "import cartopy; print('Cartopy import successful')"

      - name: Execute Python script
        shell: bash -l {0}
        run: |
          python downloadNC.py

      - name: Use Node.js
        uses: actions/setup-node@v3
      - run: npm install
      - name: "Run Node script with NODE_OPTIONS to allow deprecated SSL"
        env:
          NODE_OPTIONS: "--openssl-legacy-provider"
        run: npm run build --if-present

      - name: Commit files
        run: |
          git config --local user.email "action[bot]@github.com"
          git config --local user.name "github-actions[bot]"
          git add --all
          git commit -m "Add changes" -a || echo "No changes to commit"
          git push