name: Download and Make

on:
  schedule:
    - cron: "0 20 * * *" # runs at 20:00 UTC everyday
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libtiff5

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          activate-environment: ssta-env
          environment-file: environment.yaml
          python-version: 3.9

      - name: Install Python Dependencies
        shell: bash -l {0}
        run: |
          conda info
          conda list
          python -V

      - name: Execute Python script
        shell: bash -l {0}
        run: |
          python downloadNC.py

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Install Node dependencies
        run: npm install

      - name: Build Node project
        env:
          NODE_OPTIONS: "--openssl-legacy-provider"
        run: npm run build --if-present

      - name: Commit files
        run: |
          git config --local user.email "action[bot]@github.com"
          git config --local user.name "github-actions[bot]"
          git add --all
          git commit -m "Add changes" -a || echo "No changes to commit"
          git push origin gh-pages --force
        shell: bash